/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_2;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args){
        
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduce el valor x: ");
        int x = miScan.nextInt();
        
        System.out.println("Introduce el valor y: ");
        int y = miScan.nextInt();

        System.out.println("x = "+ x );
        System.out.println("y = "+ y );
        
        int suma = x + y; 
        System.out.println("La suma de las variables es: " + suma);
        
        int resta = x - y; 
        System.out.println("La resta de las variables es: " + resta);
        
        int multi = x * y; 
        System.out.println("La multiplicación de las variables es: " + multi);
        
        float div = (float)x / y; //(float)x es un cast, convierte la variable x en float solo en ese variable
        System.out.println("La división de las variables es: " + div);
    }
}
